import React from 'react';
import { EvaluationData } from '../api/evaluations';

interface Props {
  data: EvaluationData;
}

const EvaluationViewer: React.FC<Props> = ({ data }) => {
  return (
    <div className="bg-slate-900 rounded-xl p-6 border border-slate-800 space-y-6">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-white">Quality Metrics</h3>
        <span className="text-xs text-slate-400">
          Last updated: {new Date(data.created_at).toLocaleString()}
        </span>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 text-center">
          <div className="text-3xl font-bold text-indigo-400">{data.wer}%</div>
          <div className="text-xs text-slate-500 uppercase tracking-wider mt-1">Word Error Rate</div>
        </div>
        <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 text-center">
          <div className="text-3xl font-bold text-emerald-400">{data.cer}%</div>
          <div className="text-xs text-slate-500 uppercase tracking-wider mt-1">Char Error Rate</div>
        </div>
      </div>

      <div className="space-y-3">
        <h4 className="text-sm font-medium text-slate-300">Transcript Diff Audit</h4>
        <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 max-h-96 overflow-y-auto font-mono text-sm leading-relaxed">
          {data.alignment_data.map((part, i) => (
            <span
              key={i}
              className={`inline p-0.5 rounded ${
                part.type === 'insertion' 
                  ? 'bg-emerald-900/30 text-emerald-400 border border-emerald-900/50' 
                  : part.type === 'deletion'
                  ? 'bg-rose-900/30 text-rose-400 border border-rose-900/50 line-through'
                  : 'text-slate-300'
              }`}
            >
              {part.value}
            </span>
          ))}
        </div>
      </div>

      <div className="bg-indigo-900/20 p-4 rounded-lg border border-indigo-800/30">
        <p className="text-xs text-indigo-300 flex items-start gap-2">
          <span className="mt-0.5">ℹ️</span>
          <span>
            <b>Red Background</b> indicates words present in the Gold Standard but missing from the AI output.
            <br />
            <b>Green Background</b> indicates extra words generated by the AI.
          </span>
        </p>
      </div>
    </div>
  );
};

export default EvaluationViewer;
